[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/faa62b6b5981cfcd60a397b2ef3c700d1a382cbf/clang/include/clang-c/Index.h#L2716),
added in faa62b6b5981cfcd60a397b2ef3c700d1a382cbf.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```