Revert "Threading: Convert Optional to std::optional"
This reverts commit a97178da893c71b742fecd820fecd67a71ec0398.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'