Revert "Use-after-return sanitizer binary metadata"
This reverts commit 7a90cb73430ac18a4752c3f75646eb3aa7897f05.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'