evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit a39bb6aa8e470ff8ed71a5eb7f49fb243d304e66.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'