Revert "[lsan] On Fuchsia, don't use atexit hook for leak checks"
This reverts commit e61f109e72a5ea52c741e372ff088ee2b151104a.
This reverts commit 9f87adceb81b2fa5dafa25a0b3f5a47252bb5902.

Causes linker errors which were not fixed by the subsequent commit
either:

/home/nikic/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:503: error: undefined reference to '__asan::InstallAtExitCheckLeaks()'