Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 1a600ef5bbe947dda59fed0ae4b6992fbc3284e5 because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }