Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit 9b7df885c409eef71e4f0266ebd918104c69458e. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```