Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit cf6b5a578dd2aa2506cafbd4397324a7accc50b9.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'