Provide anchor for compiler extensions
This patch is cherry-picked from ca4bf3f6b66a3a44fca52ce62a216a90e9c7fdd6, and
amended to prevent an undefined reference to `llvm::EnableABIBreakingChecks'

(cherry picked from commit 939d25cf1dd7105ac38e3345e5d2b9da3e7b8900)