Revert "[ADT] Support const-qualified unique_functions"
This reverts commit 4060e6bfcb3bcbd9c71f10758aebc4bee33d5850.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;