Revert "lit: revert 134b103fc0f3a995d76398bf4b029d72bebe8162"
This reverts commit 7755e06243fada8e8d6518deb93870a75f744ffb.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74