Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 85df0467710afd91ba17d926c13403a868c2a0c2.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {