Revert "[lldb] Upstream support for Foundation constant classes"
This reverts commit 5e74969474f57950a6f0542f7ea7796b6c3f7eef.

This breaks build bots witha  missing file:
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/Language/ObjC/Cocoa.cpp:10:10: fatal error: 'objc/runtime.h' file not found