Revert "[FPEnv][X86] Platform-specific builtin constrained FP enablement"
This reverts commit 08c19bd82d805bcc129520261a99dbaa04c300dc.

Tests fail:
error: unable to create target: 'No available targets are compatible with triple "x86_64-apple-darwin"'

This happens on clang-hexagon-elf, clang-cmake-armv7-quick, and
clang-cmake-armv7-quick bots.

If anyone has any suggestions on why then I'm all ears.

Differential Revision: https://reviews.llvm.org/D73570

Revert "[FPEnv][X86] Speculative fix for failures introduced by eda495426."

This reverts commit 3d6ad6f7319093c18369b434883253d98e317a33.

The speculative fix didn't solve the test failures on Hexagon, ARMv6, and
MSVC AArch64.