Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit 213f9bec97e2d6b311c07f9f5595ce39bdbeedd9.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'