Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit f90556766318c12e1ddd7a3955fea5e0b0f39064.