Fix llvm-objcopy shared lib build
Fix after ec3e11aa5751 ("[llvm-objcopy][COFF] Fix section name
encoding", 2022-02-21) caused "undefined reference to
`llvm::COFF::encodeSectionName" failures.