Revert "[clang] Implement Change scope of lambda trailing-return-type"
This reverts commit 15a89b99f540d3c3102f0a502141388d56bb8509.
This broke clang bootstrap: it made existing C++ code in LLVM invalid:

llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
              [=](std::remove_reference_t<decltype(*Idx)> V,
                                                    ^