Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit 20112ae70db76b78ced77b69b9707896fb6733c0.

A bot is broken