Revert D137868 "[libc] Fix builtin definition for memory functions"
This reverts commit 52bf01749fb3e138723e969bb9d308b6a51e64d8.

This caused -Wmacro-redefined
```
.../libc/src/string/memory_utils/op_x86.h:31:9: error: '_mm512_cmpneq_epi8_mask' macro redefined [-Werror,-Wmacro-redefined]
        ^
.../lib/clang/google3-trunk/include/avx512bwintrin.h:294:9: note: previous definition is here
        ^
```