Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 9c28cea0726d6964dcc6e9b159fcd1baf6eb7567.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found