[libcxx] Bump __libcpp_version to 14 after branch
This was missed in 36849d0a534dc50c1c4836fbc55e1a7a82416ff8
and caused test failures in the buildkite bots:
libcpp_version.pass.cpp:22:1:
error: static_assert failed due to requirement '14000 == libcpp_version'
"_LIBCPP_VERSION doesn't match __libcpp_version