Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit ec6db62679993c16b30c0bdf5f3c7cf571169545.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.