Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit 20861c28a49b354df3a0df6cb87652a8e923d7f6.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {