Revert D130308 "[clang] extend getCommonSugaredType to merge sugar nodes"
This reverts commit f4e3671b23861fdf5061443d088285125ee68751.
There are multiple complaints on the review.

In addition, it may cause spurious
```
error: invalid operands to binary expression ('SinkPrinter' and 'char[cluster_name_length]')
note: candidate template ignored: substitution failure: variably modified type 'char *' cannot be used as a template argument SinkPrinter operator<<(const SinkPrinter &s, T) {
```
for some C++ code