Revert "[Tooling/Inclusion] Handle std::get symbol."
This reverts commit 2a47a1ff0aba3eb04fa82342afdcac9edbf9b9b3.

Causing many clangd test breakages, similar to:

error: no matching constructor for initialization of 'llvm::SmallVector<clang::tooling::stdlib::Header>'
                : llvm::SmallVector<clang::tooling::stdlib::Header>(
                  ^