Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit 04c194d5cd2b066d74324ce4b5dcfc741b98cfec.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```