Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit ffc22c383607ad4b827928ecdf5d3f2be46695ad.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079