Revert "[lldb] [gdb-remote client] Refactor handling qSupported"
This reverts commit 7ba111a041000ebacec5d58da02b8709613e5ec4.

It fails to build, with errors such as:
  GDBRemoteCommunicationClient.cpp:1005:20:
  error: no viable overloaded '='
          avail_name = compression;