Revert "[mlir][tosa] Split tosa-to-linalg named ops out of pass"
This reverts commit 102b595b1438738e348b9c981a6df9e28bba5a12.

There is a missing CMake dependency, building with shared libraries is
broken:

55.509 [45/4/3061] Linking CXX shared library lib/libMLIRTosaToLinalg.so.14git
FAILED: lib/libMLIRTosaToLinalg.so.14git
...
TosaToLinalgPass.cpp: undefined reference to `mlir::createCanonicalizerPass()'