Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 9af110dda2fe0aa63a2315c4ae265a5c2d556fae.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'