Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 2a49e19f1f0fef04bf019eb1b9828c91e132dfda.
Breaks building on Windows:

    ../../lldb/include\lldb/Host/HostNativeThreadBase.h(49,36): error:
        cannot initialize a member subobject of type 'lldb::thread_result_t'
        (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'
      lldb::thread_result_t m_result = nullptr;
                                       ^~~~~~~
    1 error generated.