Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit dc54b8cd8d71de1d6401df758b15715e36a447a9.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".