Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit dfdb9b0c8c1eaa3594026e1fbf33350e3cb623f7 and
7967551920ab617af511b432042a2bfe0020ab8c.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!